export let emojisList = [
    {
        "smile": "😄",
        "smiley": "😃",
        "grinning": "😀",
        "blush": "😊",
        "wink": "😉",
        "heart_eyes": "😍",
        "kissing_heart": "😘",
        "kissing_closed_eyes": "😚",
        "kissing": "😗",
        "kissing_smiling_eyes": "😙",
        "stuck_out_tongue_winking_eye": "😜",
        "stuck_out_tongue_closed_eyes": "😝",
        "stuck_out_tongue": "😛",
        "yum": "😋",
        "mask": "😷",
        "sunglasses": "😎",
        "flushed": "😳",
        "grin": "😁",
        "pensive": "😔",
        "hushed": "😯",
        "smirk": "😏",
    },
    {
        "relieved": "😌",
        "unamused": "😒",
        "disappointed": "😞",
        "persevere": "😣",
        "cry": "😢",
        "joy": "😂",
        "sob": "😭",
        "sleepy": "😪",
        "disappointed_relieved": "😥",
        "cold_sweat": "😰",
        "sweat_smile": "😅",
        "sweat": "😓",
        "weary": "😩",
        "tired_face": "😫",
        "fearful": "😨",
        "scream": "😱",
        "angry": "😠",
        "rage": "😡",
        "triumph": "😤",
        "confounded": "😖",
        "laughing": "😆",
    },
    {
        "sleeping": "😴",
        "dizzy_face": "😵",
        "astonished": "😲",
        "worried": "😟",
        "frowning": "😦",
        "anguished": "😧",
        "imp": "👿",
        "open_mouth": "😮",
        "grimacing": "😬",
        "neutral_face": "😐",
        "confused": "😕",
        "expressionless": "😑"
    }   
]