
export let  majorList = 
[{
    "value": "管理科学与工程类",
    "label": "管理科学与工程类",
    "children": [{
        "value": "管理科学",
        "label": "管理科学"
    }, {
        "value": "信息管理和信息系统",
        "label": "信息管理和信息系统"
    }, {
        "value": "工业工程",
        "label": "工业工程"
    }, {
        "value": "工程管理",
        "label": "工程管理"
    }, {
        "value": "管理科学",
        "label": "管理科学"
    }, {
        "value": "产品质量工程",
        "label": "产品质量工程"
    }]
}, {
    "value": "工商管理类",
    "label": "工商管理类",
    "children": [{
        "value": "工商管理",
        "label": "工商管理"
    }, {
        "value": "市场营销",
        "label": "市场营销"
    }, {
        "value": "商品学",
        "label": "商品学"
    }, {
        "value": "工程管理",
        "label": "工程管理"
    }, {
        "value": "会计学",
        "label": "会计学"
    }, {
        "value": "审计学",
        "label": "审计学"
    }, {
        "value": "涉外会计",
        "label": "涉外会计"
    }, {
        "value": "会计信息系统",
        "label": "会计信息系统"
    }, {
        "value": "财务管理",
        "label": "财务管理"
    }, {
        "value": "财政金融",
        "label": "财政金融"
    }, {
        "value": "资产评估",
        "label": "资产评估"
    }, {
        "value": "企业管理",
        "label": "企业管理"
    }, {
        "value": "商务策划管理",
        "label": "商务策划管理"
    }, {
        "value": "国际商务",
        "label": "国际商务"
    }, {
        "value": "电子商务",
        "label": "电子商务"
    }, {
        "value": "房地产经营管理",
        "label": "房地产经营管理"
    }, {
        "value": "物业管理",
        "label": "物业管理"
    }, {
        "value": "物流管理",
        "label": "物流管理"
    }, {
        "value": "旅游管理",
        "label": "旅游管理"
    }, {
        "value": "酒店管理",
        "label": "酒店管理"
    }, {
        "value": "连锁经营管理",
        "label": "连锁经营管理"
    }, {
        "value": "人力资源管理",
        "label": "人力资源管理"
    }]
}, {
    "value": "公共管理类",
    "label": "公共管理类",
    "children": [{
        "value": "行政管理",
        "label": "行政管理"
    }, {
        "value": "公共关系学",
        "label": "公共关系学"
    }, {
        "value": "文秘",
        "label": "文秘"
    }, {
        "value": "公共事业管理",
        "label": "公共事业管理"
    }, {
        "value": "公共政策学",
        "label": "公共政策学"
    }, {
        "value": "国防教育与管理",
        "label": "国防教育与管理"
    }, {
        "value": "劳动关系",
        "label": "劳动关系"
    }, {
        "value": "劳动与社会保障",
        "label": "劳动与社会保障"
    }, {
        "value": "城市规划与管理",
        "label": "城市规划与管理"
    }, {
        "value": "土地资源管理",
        "label": "土地资源管理"
    }, {
        "value": "农业经济管理",
        "label": "农业经济管理"
    }, {
        "value": "食品经济管理",
        "label": "食品经济管理"
    }, {
        "value": "会展经济与管理",
        "label": "会展经济与管理"
    }, {
        "value": "文化产业管理",
        "label": "文化产业管理"
    }, {
        "value": "体育产业管理",
        "label": "体育产业管理"
    }, {
        "value": "房地产经营管理",
        "label": "房地产经营管理"
    }, {
        "value": "航运管理",
        "label": "航运管理"
    }]
}, {
    "value": "图书档案学类",
    "label": "图书档案学类",
    "children": [{
        "value": "图书馆学和档案学",
        "label": "图书馆学和档案学"
    }, {
        "value": "信息资源管理",
        "label": "信息资源管理"
    }]
}, {
    "value": "电子信息科学类",
    "label": "电子信息科学类",
    "children": [{
        "value": "电子信息科学与技术",
        "label": "电子信息科学与技术"
    }, {
        "value": "光信息科学与技术",
        "label": "光信息科学与技术"
    }, {
        "value": "光电子技术科学",
        "label": "光电子技术科学"
    }, {
        "value": "微电子学",
        "label": "微电子学"
    }, {
        "value": "信息科学技术",
        "label": "信息科学技术"
    }, {
        "value": "信息安全",
        "label": "信息安全"
    }, {
        "value": "科技防卫",
        "label": "科技防卫"
    }]
}, {
    "value": "机械类",
    "label": "机械类",
    "children": [{
        "value": "机械设计制造及其自动化",
        "label": "机械设计制造及其自动化"
    }, {
        "value": "机械电子工程/机电一体化",
        "label": "机械电子工程/机电一体化"
    }, {
        "value": "机械工程及自动化",
        "label": "机械工程及自动化"
    }, {
        "value": "机械制造工艺与设备",
        "label": "机械制造工艺与设备"
    }, {
        "value": "制造工程",
        "label": "制造工程"
    }, {
        "value": "制造自动化与测控技术",
        "label": "制造自动化与测控技术"
    }, {
        "value": "材料成型及控制工程",
        "label": "材料成型及控制工程"
    }, {
        "value": "工业设计",
        "label": "工业设计"
    }, {
        "value": "过程装备与控制工程",
        "label": "过程装备与控制工程"
    }, {
        "value": "模具设计与制造",
        "label": "模具设计与制造"
    }, {
        "value": "微机电系统工程",
        "label": "微机电系统工程"
    }, {
        "value": "车辆工程",
        "label": "车辆工程"
    }, {
        "value": "汽车服务工程",
        "label": "汽车服务工程"
    }]
}, {
    "value": "仪器仪表类",
    "label": "仪器仪表类",
    "children": [{
        "value": "测控技术与仪器",
        "label": "测控技术与仪器"
    }, {
        "value": "能源动力类",
        "label": "能源动力类"
    }, {
        "value": "热能与动力工程",
        "label": "热能与动力工程"
    }, {
        "value": "电力系统及自动化",
        "label": "电力系统及自动化"
    }, {
        "value": "制冷与低温技术",
        "label": "制冷与低温技术"
    }]
}, {
    "value": "材料类",
    "label": "材料类",
    "children": [{
        "value": "材料科学与工程",
        "label": "材料科学与工程"
    }, {
        "value": "材料物理",
        "label": "材料物理"
    }, {
        "value": "材料化学",
        "label": "材料化学"
    }, {
        "value": "冶金工程",
        "label": "冶金工程"
    }, {
        "value": "金属材料工程",
        "label": "金属材料工程"
    }, {
        "value": "无机非金属材料工程",
        "label": "无机非金属材料工程"
    }, {
        "value": "高分子材料与工程",
        "label": "高分子材料与工程"
    }, {
        "value": "电子封装技术",
        "label": "电子封装技术"
    }]
}, {
    "value": "轻工纺织食品类",
    "label": "轻工纺织食品类",
    "children": [{
        "value": "食品科学与工程",
        "label": "食品科学与工程"
    }, {
        "value": "轻化工程",
        "label": "轻化工程"
    }, {
        "value": "包装工程",
        "label": "包装工程"
    }, {
        "value": "印刷工程",
        "label": "印刷工程"
    }, {
        "value": "服装设计与工程",
        "label": "服装设计与工程"
    }, {
        "value": "纺织工程",
        "label": "纺织工程"
    }]
}, {
    "value": "土建类",
    "label": "土建类",
    "children": [{
        "value": "土木工程",
        "label": "土木工程"
    }, {
        "value": "道路与桥梁",
        "label": "道路与桥梁"
    }, {
        "value": "建筑学",
        "label": "建筑学"
    }, {
        "value": "建筑工程",
        "label": "建筑工程"
    }, {
        "value": "工业与民用建筑",
        "label": "工业与民用建筑"
    }, {
        "value": "工程造价管理",
        "label": "工程造价管理"
    }, {
        "value": "建筑环境与设备工程",
        "label": "建筑环境与设备工程"
    }, {
        "value": "给排水科学与工程",
        "label": "给排水科学与工程"
    }, {
        "value": "供热通风与空调工程",
        "label": "供热通风与空调工程"
    }, {
        "value": "室内装潢设计",
        "label": "室内装潢设计"
    }, {
        "value": "城市规划",
        "label": "城市规划"
    }, {
        "value": "历史建筑保护工程",
        "label": "历史建筑保护工程"
    }, {
        "value": "景观学",
        "label": "景观学"
    }]
}, {
    "value": "交通运输类",
    "label": "交通运输类",
    "children": [{
        "value": "交通运输",
        "label": "交通运输"
    }, {
        "value": "交通工程",
        "label": "交通工程"
    }, {
        "value": "物流工程",
        "label": "物流工程"
    }, {
        "value": "油气储运工程",
        "label": "油气储运工程"
    }, {
        "value": "轮机工程",
        "label": "轮机工程"
    }, {
        "value": "飞行技术",
        "label": "飞行技术"
    }, {
        "value": "航海技术",
        "label": "航海技术"
    }, {
        "value": "海事管理",
        "label": "海事管理"
    }]
}, {
    "value": "武器类",
    "label": "武器类",
    "children": [{
        "value": "武器系统与发射工程",
        "label": "武器系统与发射工程"
    }, {
        "value": "探测制导与控制技术",
        "label": "探测制导与控制技术"
    }, {
        "value": "弹药工程与爆炸技术",
        "label": "弹药工程与爆炸技术"
    }, {
        "value": "特种能源工程与烟火技术",
        "label": "特种能源工程与烟火技术"
    }, {
        "value": "地面武器机动工程",
        "label": "地面武器机动工程"
    }, {
        "value": "信息对抗技术",
        "label": "信息对抗技术"
    }]
}, {
    "value": "天文地质地理类",
    "label": "天文地质地理类",
    "children": [{
        "value": "天文学",
        "label": "天文学"
    }, {
        "value": "地质学",
        "label": "地质学"
    }, {
        "value": "地球化学",
        "label": "地球化学"
    }, {
        "value": "地球物理学",
        "label": "地球物理学"
    }, {
        "value": "地球与空间科学",
        "label": "地球与空间科学"
    }, {
        "value": "地理科学",
        "label": "地理科学"
    }, {
        "value": "地理信息系统",
        "label": "地理信息系统"
    }, {
        "value": "地理信息科学与技术",
        "label": "地理信息科学与技术"
    }, {
        "value": "大气科学",
        "label": "大气科学"
    }, {
        "value": "海洋科学",
        "label": "海洋科学"
    }, {
        "value": "地矿",
        "label": "地矿"
    }, {
        "value": "石油工程",
        "label": "石油工程"
    }, {
        "value": "宝石鉴定与加工",
        "label": "宝石鉴定与加工"
    }]
}, {
    "value": "经济学类",
    "label": "经济学类",
    "children": [{
        "value": "经济与金融",
        "label": "经济与金融"
    }, {
        "value": "经济学",
        "label": "经济学"
    }, {
        "value": "财政学",
        "label": "财政学"
    }, {
        "value": "金融学",
        "label": "金融学"
    }, {
        "value": "经济管理",
        "label": "经济管理"
    }, {
        "value": "经济信息管理",
        "label": "经济信息管理"
    }, {
        "value": "国际经济与贸易",
        "label": "国际经济与贸易"
    }, {
        "value": "国际金融",
        "label": "国际金融"
    }, {
        "value": "贸易经济",
        "label": "贸易经济"
    }, {
        "value": "金融工程",
        "label": "金融工程"
    }, {
        "value": "投资学",
        "label": "投资学"
    }, {
        "value": "统计学",
        "label": "统计学"
    }, {
        "value": "保险",
        "label": "保险"
    }, {
        "value": "税务",
        "label": "税务"
    }, {
        "value": "信用管理",
        "label": "信用管理"
    }, {
        "value": "网络经济学",
        "label": "网络经济学"
    }, {
        "value": "技术经济",
        "label": "技术经济"
    }]
}, {
    "value": "语言文学类",
    "label": "语言文学类",
    "children": [{
        "value": "汉语言文学",
        "label": "汉语言文学"
    }, {
        "value": "对外汉语",
        "label": "对外汉语"
    }, {
        "value": "英语",
        "label": "英语"
    }, {
        "value": "商务英语",
        "label": "商务英语"
    }, {
        "value": "外贸英语",
        "label": "外贸英语"
    }, {
        "value": "俄语",
        "label": "俄语"
    }, {
        "value": "德语",
        "label": "德语"
    }, {
        "value": "法语",
        "label": "法语"
    }, {
        "value": "西班牙语",
        "label": "西班牙语"
    }, {
        "value": "阿拉伯语",
        "label": "阿拉伯语"
    }, {
        "value": "日语",
        "label": "日语"
    }, {
        "value": "朝鲜语",
        "label": "朝鲜语"
    }, {
        "value": "其它外语",
        "label": "其它外语"
    }]
}, {
    "value": "艺术类",
    "label": "艺术类",
    "children": [{
        "value": "音乐、作曲",
        "label": "音乐、作曲"
    }, {
        "value": "舞蹈",
        "label": "舞蹈"
    }, {
        "value": "美术学",
        "label": "美术学"
    }, {
        "value": "艺术设计",
        "label": "艺术设计"
    }, {
        "value": "绘画",
        "label": "绘画"
    }, {
        "value": "雕塑",
        "label": "雕塑"
    }, {
        "value": "服装设计",
        "label": "服装设计"
    }, {
        "value": "影视学",
        "label": "影视学"
    }, {
        "value": "导演、广播电视编导",
        "label": "导演、广播电视编导"
    }, {
        "value": "戏剧、表演",
        "label": "戏剧、表演"
    }, {
        "value": "戏剧影视文学",
        "label": "戏剧影视文学"
    }, {
        "value": "戏剧影视美术设计",
        "label": "戏剧影视美术设计"
    }, {
        "value": "摄影、动画",
        "label": "摄影、动画"
    }, {
        "value": "播音、主持、录音",
        "label": "播音、主持、录音"
    }]
}, {
    "value": "法学类",
    "label": "法学类",
    "children": [{
        "value": "法学",
        "label": "法学"
    }, {
        "value": "马克思主义理论",
        "label": "马克思主义理论"
    }, {
        "value": "政治学与行政学",
        "label": "政治学与行政学"
    }, {
        "value": "思想政治教育",
        "label": "思想政治教育"
    }, {
        "value": "国际政治",
        "label": "国际政治"
    }, {
        "value": "国际经济法",
        "label": "国际经济法"
    }, {
        "value": "经济法",
        "label": "经济法"
    }, {
        "value": "社会学",
        "label": "社会学"
    }, {
        "value": "外交学",
        "label": "外交学"
    }, {
        "value": "公安学",
        "label": "公安学"
    }]
}, {
    "value": "医学类",
    "label": "医学类",
    "children": [{
        "value": "基础医学",
        "label": "基础医学"
    }, {
        "value": "预防医学",
        "label": "预防医学"
    }, {
        "value": "营养学",
        "label": "营养学"
    }, {
        "value": "临床医学与医学技术",
        "label": "临床医学与医学技术"
    }, {
        "value": "麻醉学",
        "label": "麻醉学"
    }, {
        "value": "放射医学",
        "label": "放射医学"
    }, {
        "value": "眼视光学",
        "label": "眼视光学"
    }, {
        "value": "口腔医学",
        "label": "口腔医学"
    }, {
        "value": "中医学",
        "label": "中医学"
    }, {
        "value": "针灸推拿学",
        "label": "针灸推拿学"
    }, {
        "value": "法医学",
        "label": "法医学"
    }, {
        "value": "护理学",
        "label": "护理学"
    }, {
        "value": "药学",
        "label": "药学"
    }, {
        "value": "中药学",
        "label": "中药学"
    }, {
        "value": "医学检验",
        "label": "医学检验"
    }]
}, {
    "value": "农业类",
    "label": "农业类",
    "children": [{
        "value": "农学",
        "label": "农学"
    }, {
        "value": "林学",
        "label": "林学"
    }, {
        "value": "农业工程",
        "label": "农业工程"
    }, {
        "value": "森林资源",
        "label": "森林资源"
    }, {
        "value": "园林",
        "label": "园林"
    }, {
        "value": "园艺",
        "label": "园艺"
    }, {
        "value": "林业工程",
        "label": "林业工程"
    }, {
        "value": "植物生产",
        "label": "植物生产"
    }, {
        "value": "植物保护学",
        "label": "植物保护学"
    }, {
        "value": "茶学",
        "label": "茶学"
    }, {
        "value": "草业科学",
        "label": "草业科学"
    }, {
        "value": "环境生态",
        "label": "环境生态"
    }, {
        "value": "动物科学",
        "label": "动物科学"
    }, {
        "value": "动物医学",
        "label": "动物医学"
    }, {
        "value": "水产科学",
        "label": "水产科学"
    }]
}, {
    "value": "电气信息类",
    "label": "电气信息类",
    "children": [{
        "value": "电气工程及其自动化",
        "label": "电气工程及其自动化"
    }, {
        "value": "电气信息工程",
        "label": "电气信息工程"
    }, {
        "value": "通信工程",
        "label": "通信工程"
    }, {
        "value": "自动化",
        "label": "自动化"
    }, {
        "value": "电子信息工程",
        "label": "电子信息工程"
    }, {
        "value": "电子科学与技术",
        "label": "电子科学与技术"
    }, {
        "value": "集成电路设计与集成系统",
        "label": "集成电路设计与集成系统"
    }, {
        "value": "影视艺术技术",
        "label": "影视艺术技术"
    }, {
        "value": "广播电视工程",
        "label": "广播电视工程"
    }]
}, {
    "value": "计算机科学与技术类",
    "label": "计算机科学与技术类",
    "children": [{
        "value": "计算机科学与技术",
        "label": "计算机科学与技术"
    }, {
        "value": "计算机科学",
        "label": "计算机科学"
    }, {
        "value": "计算机工程",
        "label": "计算机工程"
    }, {
        "value": "计算机网络",
        "label": "计算机网络"
    }, {
        "value": "计算机应用",
        "label": "计算机应用"
    }, {
        "value": "软件工程",
        "label": "软件工程"
    }, {
        "value": "计算机信息管理",
        "label": "计算机信息管理"
    }]
}, {
    "value": "新闻传播学类",
    "label": "新闻传播学类",
    "children": [{
        "value": "新闻学",
        "label": "新闻学"
    }, {
        "value": "广播电视新闻",
        "label": "广播电视新闻"
    }, {
        "value": "广告学",
        "label": "广告学"
    }, {
        "value": "编辑出版学",
        "label": "编辑出版学"
    }, {
        "value": "传播学",
        "label": "传播学"
    }, {
        "value": "媒体创意",
        "label": "媒体创意"
    }]
}, {
    "value": "系统科学类",
    "label": "系统科学类",
    "children": [{
        "value": "系统理论",
        "label": "系统理论"
    }, {
        "value": "系统科学与工程",
        "label": "系统科学与工程"
    }]
}, {
    "value": "历史学类",
    "label": "历史学类",
    "children": [{
        "value": "历史学",
        "label": "历史学"
    }, {
        "value": "考古学",
        "label": "考古学"
    }, {
        "value": "博物馆学",
        "label": "博物馆学"
    }]
}, {
    "value": "教育学类",
    "label": "教育学类",
    "children": [{
        "value": "教育学",
        "label": "教育学"
    }, {
        "value": "体育教育",
        "label": "体育教育"
    }, {
        "value": "学前教育",
        "label": "学前教育"
    }, {
        "value": "职业技术教育",
        "label": "职业技术教育"
    }, {
        "value": "特殊教育",
        "label": "特殊教育"
    }, {
        "value": "教育技术学",
        "label": "教育技术学"
    }]
}, {
    "value": "心理学类",
    "label": "心理学类",
    "children": [{
        "value": "心理学",
        "label": "心理学"
    }, {
        "value": "应用心理学",
        "label": "应用心理学"
    }]
}, {
    "value": "化学类及化学工程类",
    "label": "化学类及化学工程类",
    "children": [{
        "value": "化学",
        "label": "化学"
    }, {
        "value": "应用化学",
        "label": "应用化学"
    }, {
        "value": "生物化工",
        "label": "生物化工"
    }, {
        "value": "化学工程与工艺",
        "label": "化学工程与工艺"
    }, {
        "value": "精细化工",
        "label": "精细化工"
    }, {
        "value": "化工设备与机械",
        "label": "化工设备与机械"
    }, {
        "value": "生物科学及生物技术类",
        "label": "生物科学及生物技术类"
    }]
}, {
    "value": "力学类",
    "label": "力学类",
    "children": [{
        "value": "力学",
        "label": "力学"
    }, {
        "value": "应用力学",
        "label": "应用力学"
    }]
}, {
    "value": "环境科学与安全类",
    "label": "环境科学与安全类",
    "children": [{
        "value": "环境科学",
        "label": "环境科学"
    }, {
        "value": "环境工程",
        "label": "环境工程"
    }, {
        "value": "安全工程",
        "label": "安全工程"
    }, {
        "value": "生态学",
        "label": "生态学"
    }]
}, {
    "value": "航空航天类",
    "label": "航空航天类",
    "children": [{
        "value": "飞行器设计与工程",
        "label": "飞行器设计与工程"
    }, {
        "value": "飞行器动力工程",
        "label": "飞行器动力工程"
    }, {
        "value": "飞行器制造工程",
        "label": "飞行器制造工程"
    }, {
        "value": "飞行器环境与生命保障工程",
        "label": "飞行器环境与生命保障工程"
    }]
}, {
    "value": "水利类、船舶与海洋类",
    "label": "水利类、船舶与海洋类",
    "children": [{
        "value": "船舶与海洋工程",
        "label": "船舶与海洋工程"
    }, {
        "value": "水利水电工程",
        "label": "水利水电工程"
    }, {
        "value": "水文与水资源工程",
        "label": "水文与水资源工程"
    }, {
        "value": "港口航道与海岸工程",
        "label": "港口航道与海岸工程"
    }]
}, {
    "value": "测绘类",
    "label": "测绘类",
    "children": [{
        "value": "测绘工程",
        "label": "测绘工程"
    }, {
        "value": "遥感科学与技术",
        "label": "遥感科学与技术"
    }, {
        "value": "空间信息与数字技术",
        "label": "空间信息与数字技术"
    }]
}, {
    "value": "生物医学、制药工程类",
    "label": "生物医学、制药工程类",
    "children": [{
        "value": "生物医学工程",
        "label": "生物医学工程"
    }, {
        "value": "制药工程",
        "label": "制药工程"
    }]
}, {
    "value": "数学类",
    "label": "数学类",
    "children": [{
        "value": "数学与应用数学",
        "label": "数学与应用数学"
    }, {
        "value": "信息与计算科学",
        "label": "信息与计算科学"
    }]
}, {
    "value": "公安技术类",
    "label": "公安技术类",
    "children": [{
        "value": "公安技术",
        "label": "公安技术"
    }]
}, {
    "value": "物理学类",
    "label": "物理学类",
    "children": [{
        "value": "物理学",
        "label": "物理学"
    }, {
        "value": "应用物理学",
        "label": "应用物理学"
    }, {
        "value": "声学",
        "label": "声学"
    }]
}, {
    "value": "生物科学，技术",
    "label": "生物科学，技术",
    "children": [{
        "value": "生物工程",
        "label": "生物工程"
    }, {
        "value": "生物信息学",
        "label": "生物信息学"
    }]
}, {
    "value": "哲学类",
    "label": "哲学类",
    "children": [{
        "value": "哲学(含伦理学)",
        "label": "哲学(含伦理学)"
    }, {
        "value": "逻辑学",
        "label": "逻辑学"
    }, {
        "value": "宗教学",
        "label": "宗教学"
    }]
}]